# Header information

intro_text: 'Using data from SOURCE'
report_header_info:
  - Series: 'GSEXXXXXX'
  - BioProject: 'PRJNAXXXXXX'
  - SRA: 'SRPXXXXXX'
  - Platform: 'PLATFORM'
  - Setup: 'SETUP'
  - Organism: 'ORGANISM'

# Module order

module_order:
  - fastqc:
      name: 'FastQC'
      anchor: 'fastqc'
      path_filters:
        - '*_[12]_fastqc.zip'
  - fastqc:
      name: 'FastQC (trimmed)'
      anchor: 'fastqc_trimmed'
      path_filters:
        - '*_[12]_paired_fastqc.zip'
  - star
  - picard:
      name: 'Picard'
      anchor: 'picard'
      path_filters:
        - '*_sorted.*'
  - picard:
      name: 'MarkDuplicates'
      anchor: 'picard_markduplicates'
      path_filters:
        - '*_deduped.log'
  - picard:
      name: 'Picard (deduped)'
      anchor: 'picard_deduped'
      path_filters:
        - '*_deduped.[!l]*'
  - featureCounts:
      name: 'FeatureCounts'
      anchor: 'featurecounts'
      path_filters:
        - '*counts.txt.summary'
