# Header information

intro_text: 'Using data from "Cerium Oxide Nanoparticle Administration to Skeletal Muscle Cells under Different Gravity and Radiation Conditions" (Genchi, 2021)'
report_header_info:
  - Series: 'GSE165565'
  - BioProject: 'PRJNA694971'
  - SRA: 'SRP303354'
  - Platform: 'Illumina HiSeq 2500 System'
  - Setup: '2x150'
  - Organism: 'Mus musculus'

# Module order

module_order:
  - fastqc:
      name: 'FastQC'
      anchor: 'fastqc'
      path_filters:
        - '*_[12]_fastqc.zip'
  - fastqc:
      name: 'FastQC (trimmed)'
      anchor: 'fastqc_trimmed'
      path_filters:
        - '*_[12]_paired_fastqc.zip'
  - star
  - picard:
      name: 'Picard'
      anchor: 'picard'
      path_filters:
        - '*_sorted.*'
  - picard:
      name: 'MarkDuplicates'
      anchor: 'picard_markduplicates'
      path_filters:
        - '*_deduped.log'
  - picard:
      name: 'Picard (deduped)'
      anchor: 'picard_deduped'
      path_filters:
        - '*_deduped.[!l]*'
  - featureCounts:
      name: 'FeatureCounts'
      anchor: 'featurecounts'
      path_filters:
        - '*counts.txt.summary'
